/*!
 * This file is part of SmartServoFramework.
 * Copyright (c) 2014, INRIA, All rights reserved.
 *
 * SmartServoFramework is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this software. If not, see <http://www.gnu.org/licenses/lgpl-3.0.txt>.
 *
 * \file SmartServoFramework_settings.h
 * \date 2016
 * \author Emeric Grange <emeric.grange@gmail.com>
 */

#ifndef SMARTSERVOFRAMEWORK_SETTINGS_H
#define SMARTSERVOFRAMEWORK_SETTINGS_H

// !!! EVERY TIMES CMAKE IS RUN, THIS FILE WILL BE REGENERATED !!!
// SmartServoFramework_settings.h.in is the template
// SmartServoFramework_settings.h is generated by cmake from the template

/* ************************************************************************** */

#define SmartServoFramework_VERSION_MAJOR 0
#define SmartServoFramework_VERSION_MINOR 0
#define SmartServoFramework_VERSION_PATCH 0

#define ENABLE_DEBUG        1  //!< Toggle debug and trace output
#define ENABLE_COLORS       1  //!< Toggle colored terminal output

/* ************************************************************************** */
#endif // SMARTSERVOFRAMEWORK_SETTINGS_H
